2018-05-25 07:32:35.526 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.164.0> exit with reason normal in context child_terminated
2018-05-25 07:32:35.564 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 07:32:35.565 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 07:32:35.567 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 07:32:35.568 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 07:32:35.571 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 07:32:35.573 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 07:32:35.590 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 07:32:35.590 [error] <0.215.0>@Elixir.Procon.Application:start_erl_kaf:23 CRASH REPORT Process <0.215.0> with 0 neighbours exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23 in application_master:init/4 line 134
2018-05-25 07:32:35.611 [info] <0.33.0>@Elixir.Procon.Application:start_erl_kaf:23 Application procon exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23
2018-05-25 07:33:10.649 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 07:33:10.688 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 07:33:10.690 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 07:33:10.692 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 07:33:10.693 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 07:33:10.695 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 07:33:10.697 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 07:33:10.709 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 07:33:10.709 [error] <0.192.0>@Elixir.Procon.Application:start_erl_kaf:23 CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23 in application_master:init/4 line 134
2018-05-25 07:33:10.737 [info] <0.33.0>@Elixir.Procon.Application:start_erl_kaf:23 Application procon exited with reason: no match of right hand value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.83746866>}] in 'Elixir.Procon.Application':start_erl_kaf/0 line 23
2018-05-25 07:34:00.554 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 07:34:00.591 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 07:34:00.593 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 07:34:00.594 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 07:34:00.595 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 07:34:00.597 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 07:34:00.598 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 07:34:00.609 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 07:34:00.609 [error] <0.192.0>@Elixir.Procon.Application:start CRASH REPORT Process <0.192.0> with 0 neighbours exited with reason: bad return value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.113779979>}] from 'Elixir.Procon.Application':start(normal, []) in application_master:init/4 line 134
2018-05-25 07:34:00.635 [info] <0.33.0>@Elixir.Procon.Application:start Application procon exited with reason: bad return value [{bootstrap_servers,<<"localhost:9092">>},{delivery_report_only_error,false},{delivery_report_callback,#Fun<Elixir.Procon.Application.0.113779979>}] from 'Elixir.Procon.Application':start(normal, [])
2018-05-25 07:34:20.441 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 07:34:20.478 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 07:34:20.480 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 07:34:20.482 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 07:34:20.483 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 07:34:20.486 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 07:34:20.487 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 07:34:20.500 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 07:34:20.500 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 09:41:50.567 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:41:50.601 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 09:41:50.603 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 09:41:50.604 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 09:41:50.605 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 09:41:50.608 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 09:41:50.609 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 09:41:50.620 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 09:41:50.651 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 09:41:50.667 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 09:41:51.696 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.102247880>:delivery_report error: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {erlkaf_msg,<<"refresh_events">>,2,0,<<"azer">>,<<"coucou">>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,22}]},{'Elixir.Procon.Application',delivery_report,2,[{file,"lib/procon/application.ex"},{line,34}]},{erlkaf_producer,handle_info,2,[{file,"/Users/ceissen/labs/papayecube/procon/procon/deps/erlkaf/src/erlkaf_producer.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
2018-05-25 09:45:23.639 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:45:23.667 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 09:45:23.669 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 09:45:23.671 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 09:45:23.672 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 09:45:23.675 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 09:45:23.676 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 09:45:23.686 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 09:45:23.705 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 09:45:23.718 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 09:45:24.744 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.53185462>:delivery_report error: {'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.String.Chars',value => {erlkaf_msg,<<"refresh_events">>,2,1,<<"azer">>,<<"coucou">>}},[{'Elixir.String.Chars','impl_for!',1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,3}]},{'Elixir.String.Chars',to_string,1,[{file,"/private/tmp/elixir-20180507-68757-17gx35t/elixir-1.6.5/lib/elixir/lib/string/chars.ex"},{line,22}]},{'Elixir.Procon.Application',delivery_report,2,[{file,"lib/procon/application.ex"},{line,34}]},{erlkaf_producer,handle_info,2,[{file,"/Users/ceissen/labs/papayecube/procon/procon/deps/erlkaf/src/erlkaf_producer.erl"},{line,79}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}
2018-05-25 09:47:48.701 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:47:48.732 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 09:47:48.734 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 09:47:48.736 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 09:47:48.737 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 09:47:48.739 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 09:47:48.740 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 09:47:48.751 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 09:47:48.767 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 09:47:48.779 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 09:47:49.796 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.83072852>:delivery_report error: {erlkaf_msg,<<"refresh_events">>,2,2,<<"azer">>,<<"coucou">>}
2018-05-25 09:48:29.728 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 09:48:29.765 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 09:48:29.767 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 09:48:29.769 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 09:48:29.770 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 09:48:29.773 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 09:48:29.774 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 09:48:29.782 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 09:48:29.797 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 09:48:29.810 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:08:11.024 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:11.067 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:08:11.069 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:08:11.071 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:08:11.071 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:08:11.074 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:08:11.076 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:08:11.091 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:08:11.116 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:08:11.125 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:08:42.199 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:42.230 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:08:42.232 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:08:42.234 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:08:42.235 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:08:42.238 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:08:42.239 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:08:42.252 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:08:42.271 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:08:42.280 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:08:59.700 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:08:59.734 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:08:59.736 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:08:59.738 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:08:59.739 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:08:59.741 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:08:59.743 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:08:59.754 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:08:59.768 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:08:59.780 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:09:00.795 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.83072852>:delivery_report error: {erlkaf_msg,<<"refresh_events">>,2,6,<<"azer">>,<<"coucou">>}
2018-05-25 10:29:30.624 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:29:30.669 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:29:30.674 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:29:30.676 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:29:30.676 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:29:30.679 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:29:30.680 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:29:30.691 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:29:30.717 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:29:30.726 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:29:31.741 [error] <0.194.0>@erlkaf_producer:handle_info:83 #Fun<Elixir.Procon.Application.0.59063235>:delivery_report error: <<"refresh_events">>
2018-05-25 10:30:19.944 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:30:19.980 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:30:19.981 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:30:19.983 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:30:19.984 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:30:19.986 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:30:19.988 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:30:19.998 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:30:20.013 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:30:20.026 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-25 10:30:38.880 [error] <0.136.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.141.0> exit with reason normal in context child_terminated
2018-05-25 10:30:38.915 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-25 10:30:38.917 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-25 10:30:38.918 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-25 10:30:38.919 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-25 10:30:38.922 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-25 10:30:38.923 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-25 10:30:38.931 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-25 10:30:38.945 [info] <0.194.0>@erlkaf_local_queue:new:15 persistent queue path: "/Users/ceissen/labs/papayecube/procon/procon/_build/dev/lib/erlkaf/priv/client_producer"
2018-05-25 10:30:38.954 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 10:19:11.641 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 10:19:11.684 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 10:19:11.687 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 10:19:11.689 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 10:19:11.690 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 10:19:11.695 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 10:19:11.696 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 10:19:11.717 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 10:19:11.729 [error] <0.270.0>@gen_tcp:connect:149 CRASH REPORT Process <0.270.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-28 10:19:11.760 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 10:20:26.041 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 10:20:26.069 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 10:20:26.072 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 10:20:26.074 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 10:20:26.075 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 10:20:26.080 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 10:20:26.081 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 10:20:26.099 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 10:20:26.100 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 10:21:18.154 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 10:21:18.196 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 10:21:18.199 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 10:21:18.201 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 10:21:18.202 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 10:21:18.206 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 10:21:18.208 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 10:21:18.220 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 10:21:18.301 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 14:48:37.436 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:48:37.464 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:48:37.466 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:48:37.469 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:48:37.470 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:48:37.475 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:48:37.477 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:48:37.497 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:48:37.548 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 14:49:28.140 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:49:28.174 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:49:28.177 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:49:28.179 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:49:28.180 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:49:28.184 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:49:28.186 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:49:28.197 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:49:28.246 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 14:49:28.274 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => nil} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 14:50:05.781 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:50:05.818 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:50:05.821 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:50:05.824 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:50:05.825 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:50:05.829 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:50:05.831 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:50:05.843 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:50:05.887 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 14:52:40.032 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:52:40.066 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:52:40.069 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:52:40.072 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:52:40.073 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:52:40.077 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:52:40.079 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:52:40.091 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:52:40.152 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 14:58:25.320 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:58:25.353 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:58:25.356 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:58:25.359 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:58:25.360 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:58:25.365 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:58:25.366 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:58:25.379 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:58:25.419 [error] <0.268.0>@Elixir.List:keyfind:265 CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265 in application_master:init/4 line 134
2018-05-28 14:58:25.453 [info] <0.33.0>@Elixir.List:keyfind:265 Application procon exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265
2018-05-28 14:59:43.799 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 14:59:43.826 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 14:59:43.829 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 14:59:43.832 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 14:59:43.833 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 14:59:43.837 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 14:59:43.838 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 14:59:43.849 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 14:59:43.908 [error] <0.268.0>@Elixir.List:keyfind:265 CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265 in application_master:init/4 line 134
2018-05-28 14:59:43.926 [info] <0.33.0>@Elixir.List:keyfind:265 Application procon exited with reason: bad argument in call to lists:keyfind(topic_metadata, 1, {kafka_metadata,[{brokers,[[{node_id,0},{host,<<"localhost">>},{port,9092},{rack,undefined}]]},{...},...]}) in 'Elixir.List':keyfind/4 line 265
2018-05-28 15:00:43.251 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:00:43.281 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:00:43.284 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:00:43.287 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:00:43.288 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:00:43.292 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:00:43.293 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:00:43.304 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:00:43.375 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:00:43.403 [info] <0.33.0>@Elixir.List:keyfind Application procon exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic)
2018-05-28 15:01:08.282 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:01:08.315 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:01:08.318 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:01:08.321 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:01:08.322 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:01:08.326 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:01:08.328 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:01:08.339 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:01:08.397 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:01:08.423 [info] <0.33.0>@Elixir.List:keyfind Application procon exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic)
2018-05-28 15:01:32.106 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:01:32.135 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:01:32.138 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:01:32.140 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:01:32.141 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:01:32.146 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:01:32.147 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:01:32.161 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:01:32.221 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:01:32.243 [info] <0.33.0>@Elixir.List:keyfind Application procon exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic)
2018-05-28 15:02:16.370 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:02:16.405 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:02:16.409 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:02:16.412 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:02:16.413 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:02:16.417 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:02:16.418 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:02:16.431 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:02:16.494 [error] <0.268.0>@Elixir.List:keyfind CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic) in application_master:init/4 line 134
2018-05-28 15:02:16.518 [info] <0.33.0>@Elixir.List:keyfind Application procon exited with reason: call to undefined function 'Elixir.List':keyfind([{topic_error_code,no_error},{topic,<<"refresh_events">>},{is_internal,false},{partition_metadata,...}], topic)
2018-05-28 15:03:06.391 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:03:06.426 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:03:06.429 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:03:06.432 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:03:06.433 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:03:06.437 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:03:06.438 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:03:06.449 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:03:06.514 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:03:06.528 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 15:03:38.119 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:03:38.152 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:03:38.155 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:03:38.158 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:03:38.159 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:03:38.163 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:03:38.165 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:03:38.176 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:03:38.237 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:03:38.257 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 15:04:50.757 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:04:50.790 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:04:50.793 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:04:50.796 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:04:50.797 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:04:50.801 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:04:50.802 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:04:50.813 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:04:50.875 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:04:50.889 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 15:05:29.064 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:05:29.097 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:05:29.101 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:05:29.103 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:05:29.104 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:05:29.109 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:05:29.110 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:05:29.123 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:05:29.193 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:05:29.208 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 15:05:46.766 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:05:46.802 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:05:46.805 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:05:46.808 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:05:46.809 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:05:46.814 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:05:46.815 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:05:46.828 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:05:46.900 [error] <0.268.0> CRASH REPORT Process <0.268.0> with 0 neighbours exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1 in application_master:init/4 line 134
2018-05-28 15:05:46.917 [info] <0.33.0> Application procon exited with reason: #{'__exception__' => true,'__struct__' => 'Elixir.Protocol.UndefinedError',description => <<>>,protocol => 'Elixir.Enumerable',value => {partition_metadata,[[{partition_error_code,no_error},{partition_id,2},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,1},{leader,0},{replicas,[0]},{isr,[0]}],[{partition_error_code,no_error},{partition_id,0},{leader,0},{replicas,[0]},{isr,[0]}]]}} in 'Elixir.Enumerable':'impl_for!'/1 line 1
2018-05-28 15:06:37.175 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:06:37.208 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:06:37.211 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:06:37.214 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:06:37.215 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:06:37.220 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:06:37.221 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:06:37.235 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:06:37.280 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 15:41:26.112 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:41:26.141 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:41:26.144 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:41:26.147 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:41:26.148 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:41:26.153 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:41:26.155 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:41:26.171 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:41:26.216 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 15:42:46.236 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:42:46.272 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:42:46.275 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:42:46.278 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:42:46.279 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:42:46.283 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:42:46.284 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:42:46.296 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:42:46.338 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 15:45:04.795 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:45:04.830 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:45:04.833 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:45:04.836 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:45:04.837 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:45:04.842 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:45:04.843 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:45:04.856 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:45:04.897 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 15:53:55.275 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 15:53:55.304 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 15:53:55.307 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 15:53:55.310 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 15:53:55.311 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 15:53:55.316 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 15:53:55.318 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 15:53:55.333 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 15:53:55.376 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 16:28:18.280 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 16:28:18.329 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 16:28:18.333 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 16:28:18.335 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 16:28:18.336 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 16:28:18.341 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 16:28:18.343 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 16:28:18.359 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 16:28:18.420 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:22:56.367 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:22:56.394 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:22:56.396 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:22:56.399 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:22:56.400 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:22:56.405 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:22:56.407 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:22:56.423 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:22:56.469 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:24:04.303 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:24:04.343 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:24:04.346 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:24:04.349 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:24:04.350 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:24:04.355 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:24:04.356 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:24:04.369 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:24:04.409 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:26:10.455 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:26:10.486 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:26:10.488 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:26:10.491 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:26:10.492 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:26:10.496 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:26:10.498 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:26:10.509 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:26:10.552 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:28:02.871 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:28:02.905 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:28:02.908 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:28:02.911 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:28:02.912 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:28:02.916 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:28:02.917 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:28:02.929 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:28:02.973 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:29:06.372 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:29:06.406 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:29:06.408 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:29:06.412 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:29:06.413 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:29:06.417 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:29:06.419 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:29:06.430 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:29:06.475 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:34:00.302 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:34:00.329 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:34:00.332 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:34:00.335 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:34:00.336 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:34:00.340 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:34:00.341 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:34:00.352 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:34:00.397 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 17:38:55.589 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 17:38:55.624 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 17:38:55.627 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 17:38:55.630 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 17:38:55.631 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 17:38:55.636 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 17:38:55.637 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 17:38:55.647 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 17:38:55.696 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 22:04:15.984 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 22:04:16.012 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 22:04:16.015 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 22:04:16.018 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 22:04:16.018 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 22:04:16.023 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 22:04:16.025 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 22:04:16.043 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 22:04:16.108 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-28 22:04:22.839 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-28 22:04:22.870 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-28 22:04:22.873 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-28 22:04:22.876 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-28 22:04:22.877 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-28 22:04:22.881 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-28 22:04:22.882 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-28 22:04:22.893 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-28 22:04:22.940 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 09:31:19.195 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 09:31:19.224 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 09:31:19.227 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 09:31:19.230 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 09:31:19.231 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 09:31:19.236 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 09:31:19.237 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 09:31:19.255 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 09:31:19.301 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:22:57.728 [error] <0.189.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.194.0> exit with reason normal in context child_terminated
2018-05-29 22:22:57.761 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:22:57.764 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:22:57.766 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:22:57.767 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:22:57.772 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:22:57.773 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:22:57.792 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:22:57.844 [error] <0.283.0>@gen_tcp:connect:149 CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:22:57.877 [warning] <0.282.0> brod_client [<0.282.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:22:57.881 [error] <0.282.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:22:57.881 [error] <0.282.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:22:57.882 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:22:57.882 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.282.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:07.845 [error] <0.288.0>@gen_tcp:connect:149 CRASH REPORT Process <0.288.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:07.846 [warning] <0.287.0> brod_client [<0.287.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:07.847 [error] <0.287.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:07.847 [error] <0.287.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:07.847 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.287.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:17.847 [error] <0.290.0>@gen_tcp:connect:149 CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:17.847 [warning] <0.289.0> brod_client [<0.289.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:17.848 [error] <0.289.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:17.848 [error] <0.289.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:17.848 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.289.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:27.847 [error] <0.292.0>@gen_tcp:connect:149 CRASH REPORT Process <0.292.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:27.848 [warning] <0.291.0> brod_client [<0.291.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:27.849 [error] <0.291.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:27.849 [error] <0.291.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:27.849 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.291.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:37.849 [error] <0.294.0>@gen_tcp:connect:149 CRASH REPORT Process <0.294.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:37.850 [warning] <0.293.0> brod_client [<0.293.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:37.850 [error] <0.293.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:37.850 [error] <0.293.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:37.850 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.293.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:47.850 [error] <0.296.0>@gen_tcp:connect:149 CRASH REPORT Process <0.296.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:47.851 [warning] <0.295.0> brod_client [<0.295.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:47.851 [error] <0.295.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:47.851 [error] <0.295.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:47.851 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.295.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:23:57.851 [error] <0.298.0>@gen_tcp:connect:149 CRASH REPORT Process <0.298.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:23:57.852 [warning] <0.297.0> brod_client [<0.297.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:23:57.852 [error] <0.297.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:57.852 [error] <0.297.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:23:57.853 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.297.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:07.852 [error] <0.300.0>@gen_tcp:connect:149 CRASH REPORT Process <0.300.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:24:07.853 [warning] <0.299.0> brod_client [<0.299.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:24:07.853 [error] <0.299.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:07.853 [error] <0.299.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:07.854 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.299.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:17.853 [error] <0.302.0>@gen_tcp:connect:149 CRASH REPORT Process <0.302.0> with 0 neighbours exited with reason: bad argument in gen_tcp:connect/4 line 149
2018-05-29 22:24:17.853 [warning] <0.301.0> brod_client [<0.301.0>] brod_client_1 is terminating
reason: {{badarg,[{<<"localhost">>,9092}]},[{brod_client,start_metadata_socket,5,[{file,"src/brod_client.erl"},{line,708}]},{brod_client,handle_info,2,[{file,"src/brod_client.erl"},{line,301}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2018-05-29 22:24:17.854 [error] <0.301.0> gen_server brod_client_1 terminated with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:17.854 [error] <0.301.0> CRASH REPORT Process brod_client_1 with 0 neighbours crashed with reason: {badarg,[{<<"localhost">>,9092}]}
2018-05-29 22:24:17.854 [error] <0.201.0> Supervisor brod_sup had child brod_client_1 started with brod_client:start_link([{<<"localhost">>,9092}], brod_client_1, [{reconnect_cool_down_seconds,10}]) at <0.301.0> exit with reason {badarg,[{<<"localhost">>,9092}]} in context child_terminated
2018-05-29 22:24:21.849 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:24:21.885 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:24:21.888 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:24:21.891 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:24:21.892 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:24:21.896 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:24:21.897 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:24:21.908 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:24:21.952 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:25:32.611 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:25:32.650 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:25:32.653 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:25:32.656 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:25:32.657 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:25:32.661 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:25:32.662 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:25:32.673 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:25:32.728 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:28:55.667 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:28:55.711 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:28:55.714 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:28:55.717 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:28:55.718 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:28:55.723 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:28:55.724 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:28:55.738 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:28:55.815 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 22:28:55.827 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:34:52.077 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:34:52.123 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:34:52.126 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:34:52.129 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:34:52.130 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:34:52.134 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:34:52.135 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:34:52.149 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:34:52.231 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 22:34:52.231 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:35:17.831 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 22:35:17.866 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 22:35:17.870 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 22:35:17.873 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 22:35:17.874 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 22:35:17.878 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 22:35:17.880 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 22:35:17.892 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 22:35:17.976 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 22:35:17.976 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 22:45:17.986 [info] <0.273.0> client brod_client_1 metadata socket down localhost:9092
Reason:{shutdown,tcp_closed}
2018-05-29 22:45:18.047 [info] <0.273.0> client brod_client_1: payload socket down localhost:9092
reason:{shutdown,tcp_closed}
2018-05-29 23:16:27.304 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:16:27.336 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:16:27.339 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:16:27.342 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:16:27.343 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:16:27.347 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:16:27.348 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:16:27.360 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:16:27.444 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:16:27.444 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:18:00.149 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:18:00.186 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:18:00.189 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:18:00.191 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:18:00.192 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:18:00.196 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:18:00.198 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:18:00.208 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:18:00.293 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:18:00.293 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:20:32.650 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:20:32.689 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:20:32.692 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:20:32.694 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:20:32.695 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:20:32.699 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:20:32.701 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:20:32.712 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:20:32.790 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:20:32.790 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:23:20.716 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:23:20.757 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:23:20.760 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:23:20.763 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:23:20.764 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:23:20.767 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:23:20.768 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:23:20.780 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:23:20.855 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:23:20.855 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:23:41.321 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:23:41.355 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:23:41.358 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:23:41.361 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:23:41.362 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:23:41.366 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:23:41.367 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:23:41.380 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:23:41.459 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:23:41.459 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:26:28.759 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:26:28.804 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:26:28.807 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:26:28.810 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:26:28.810 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:26:28.814 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:26:28.815 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:26:28.827 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:26:28.903 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:26:28.911 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:27:06.655 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:27:06.692 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:27:06.695 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:27:06.698 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:27:06.699 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:27:06.703 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:27:06.704 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:27:06.716 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:27:06.794 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:27:06.831 [error] <0.280.0>@brod_utils:bytes:492 gen_server <0.280.0> terminated with reason: no function clause matching brod_utils:bytes(256) line 492
2018-05-29 23:27:06.831 [error] <0.280.0>@brod_utils:bytes:492 CRASH REPORT Process <0.280.0> with 0 neighbours crashed with reason: no function clause matching brod_utils:bytes(256) line 492
2018-05-29 23:27:06.831 [error] <0.277.0>@brod_utils:bytes:492 Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason no function clause matching brod_utils:bytes(256) line 492 in context child_terminated
2018-05-29 23:27:06.831 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:27:27.889 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:27:27.922 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:27:27.925 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:27:27.928 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:27:27.928 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:27:27.932 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:27:27.933 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:27:27.944 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:27:28.016 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:27:28.041 [error] <0.280.0>@kpro:encode:297 gen_server <0.280.0> terminated with reason: no function clause matching kpro:encode(bytes, 1) line 297
2018-05-29 23:27:28.042 [error] <0.280.0>@kpro:encode:297 CRASH REPORT Process <0.280.0> with 0 neighbours crashed with reason: no function clause matching kpro:encode(bytes, 1) line 297
2018-05-29 23:27:28.042 [error] <0.277.0>@kpro:encode:297 Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason no function clause matching kpro:encode(bytes, 1) line 297 in context child_terminated
2018-05-29 23:27:28.042 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:28:00.470 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:28:00.503 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:28:00.506 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:28:00.509 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:28:00.510 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:28:00.514 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:28:00.515 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:28:00.525 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:28:00.596 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:28:00.600 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:28:14.633 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:28:14.666 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:28:14.669 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:28:14.671 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:28:14.672 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:28:14.676 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:28:14.677 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:28:14.688 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:28:14.759 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:28:14.772 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:28:51.328 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:28:51.362 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:28:51.364 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:28:51.367 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:28:51.368 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:28:51.372 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:28:51.373 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:28:51.383 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:28:51.459 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:28:51.565 [info] <0.33.0> Application procon started on node nonode@nohost
2018-05-29 23:29:19.785 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-29 23:29:19.821 [info] <0.33.0> Application lager started on node nonode@nohost
2018-05-29 23:29:19.825 [info] <0.33.0> Application jsone started on node nonode@nohost
2018-05-29 23:29:19.827 [info] <0.33.0> Application feta started on node nonode@nohost
2018-05-29 23:29:19.828 [info] <0.33.0> Application datum started on node nonode@nohost
2018-05-29 23:29:19.833 [info] <0.33.0> Application pipe started on node nonode@nohost
2018-05-29 23:29:19.834 [info] <0.33.0> Application esq started on node nonode@nohost
2018-05-29 23:29:19.846 [info] <0.33.0> Application erlkaf started on node nonode@nohost
2018-05-29 23:29:19.924 [info] <0.273.0> client brod_client_1 connected to localhost:9092
2018-05-29 23:29:21.149 [error] <0.280.0> Error in produce response
Topic: refresh_events Partition: 2 Offset: -1 Error: 'MessageTooLarge'
2018-05-29 23:29:21.217 [error] <0.280.0> gen_server <0.280.0> terminated with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-29 23:29:21.217 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-29 23:29:21.217 [error] <0.277.0> Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in context child_terminated
2018-05-29 23:29:21.217 [info] <0.33.0> Application procon started on node nonode@nohost
