2018-05-31 18:14:03.371 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
2018-05-31 18:14:04.735 [error] <0.280.0> Error in produce response
Topic: refresh_events Partition: 2 Offset: -1 Error: 'MessageTooLarge'
2018-05-31 18:14:04.831 [error] <0.280.0> gen_server <0.280.0> terminated with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-31 18:14:04.832 [error] <0.280.0> CRASH REPORT Process <0.280.0> with 0 neighbours exited with reason: {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in brod_producer:handle_info/2 line 317
2018-05-31 18:14:04.832 [error] <0.277.0> Supervisor {<0.277.0>,brod_producers_sup} had child 2 started with brod_producer:start_link(<0.273.0>, <<"refresh_events">>, 2, []) at <0.280.0> exit with reason {not_retriable,{produce_response_error,<<"refresh_events">>,2,-1,'MessageTooLarge'}} in context child_terminated
2018-05-31 18:14:44.166 [error] <0.180.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.185.0> exit with reason normal in context child_terminated
